name: advicer_app
description: 'Advicer APP: Example of clean structure based app implementation'

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  bloc: ^8.1.1
  dartz: ^0.10.1
  http: ^0.13.5
  envied: ^0.3.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  envied_generator: ^0.3.0
  build_runner: ^2.3.3

  test: ^1.22.0
  mockito: ^5.4.0

flutter:
  uses-material-design: true
